version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build || echo "No build script found, skipping..."

  post_build:
    commands:
      - echo "Zipping the application..."
      - zip -r node-app.zip .

artifacts:
  files:
    - node-app.zip
    - appspec.yml
    - scripts/start.sh
  discard-paths: no
